import assert from "node:assert/strict";
import { after, test } from "node:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import esbuild from "esbuild";

let tempDir;
let modulePromise;

async function loadModule() {
	if (modulePromise) return modulePromise;
	modulePromise = (async () => {
		tempDir = await mkdtemp(path.join(os.tmpdir(), "health-md-dashboard-tests-"));
		const outfile = path.join(tempDir, "dashboard-note.mjs");
		const harness = path.join(tempDir, "dashboard-note-harness.ts");
		await writeFile(harness, `
export * from ${JSON.stringify(path.join(process.cwd(), "src/dashboard-note.ts"))};
export * from ${JSON.stringify(path.join(process.cwd(), "src/visualization-catalog.ts"))};
`, "utf8");
		await esbuild.build({
			entryPoints: [harness],
			bundle: true,
			platform: "node",
			format: "esm",
			outfile,
			logLevel: "silent",
		});
		return import(pathToFileURL(outfile).href);
	})();
	return modulePromise;
}

after(async () => {
	if (tempDir) await rm(tempDir, { recursive: true, force: true });
});

test("dashboard documents every visualization in the catalog", async () => {
	const { buildDashboardMarkdown, VISUALIZATION_CATALOG } = await loadModule();
	const markdown = buildDashboardMarkdown("9.9.9");
	for (const option of VISUALIZATION_CATALOG) {
		assert.ok(markdown.includes(`### ${option.label}`), `missing heading for ${option.type}`);
		assert.ok(
			markdown.includes(`type: ${option.type}\n`),
			`missing example block for ${option.type}`
		);
		assert.ok(
			markdown.includes(`\`${option.type}\` · Works with:`),
			`missing export-source line for ${option.type}`
		);
	}
});

test("every catalog type appears inside a health-viz example fence", async () => {
	const { buildDashboardMarkdown, VISUALIZATION_CATALOG } = await loadModule();
	const markdown = buildDashboardMarkdown("9.9.9");
	const blocks = markdown.split("```health-viz\n").slice(1)
		.map((chunk) => chunk.split("\n```")[0]);
	assert.equal(blocks.length, VISUALIZATION_CATALOG.length);
	for (const option of VISUALIZATION_CATALOG) {
		const block = blocks.find((candidate) => candidate.startsWith(`type: ${option.type}\n`));
		assert.ok(block, `no example block starts with type: ${option.type}`);
		assert.ok(block.includes(`last: ${option.defaultLast}`), `${option.type} block missing last`);
		if (option.defaultHeight != null) {
			assert.ok(block.includes(`height: ${option.defaultHeight}`), `${option.type} block missing height`);
		}
	}
});

test("dashboard includes category sections, contents links, and defaults tables", async () => {
	const { buildDashboardMarkdown, VISUALIZATION_CATEGORIES } = await loadModule();
	const markdown = buildDashboardMarkdown("9.9.9");
	for (const category of VISUALIZATION_CATEGORIES) {
		if (category.id === "all") continue;
		assert.ok(markdown.includes(`## ${category.label}`), `missing category ${category.label}`);
		assert.ok(markdown.includes(`[[#${category.label}]]`), `missing contents link for ${category.label}`);
	}
	assert.match(markdown, /# Health\.md visualizations/);
	assert.match(markdown, /\| Option \| Description \| Default \|/);
	assert.match(markdown, /Regenerate health dashboard/);
	assert.match(markdown, /Generated by Health\.md Visualizations v9\.9\.9/);
});

test("dashboard documents the real-data requirement and store links", async () => {
	const { buildDashboardMarkdown } = await loadModule();
	const markdown = buildDashboardMarkdown("9.9.9");
	assert.match(markdown, /Charts need real data/);
	assert.match(markdown, /ships with no sample data/);
	assert.match(markdown, /apps\.apple\.com\/us\/app\/health-md\/id6757763969/);
	assert.match(markdown, /play\.google\.com\/store\/apps\/details\?id=com\.healthmd\.android/);
	// Store links appear before the first visualization section.
	const firstSection = markdown.indexOf("## ");
	assert.ok(firstSection > 0, "dashboard has category sections");
	assert.ok(markdown.indexOf("apps.apple.com") < firstSection, "App Store link should be near the top");
	assert.ok(markdown.indexOf("play.google.com") < firstSection, "Play Store link should be near the top");
});

test("example blocks mirror catalog defaults (spot checks)", async () => {
	const { buildDashboardMarkdown } = await loadModule();
	const markdown = buildDashboardMarkdown("9.9.9");
	const blocks = markdown.split("```health-viz\n").slice(1)
		.map((chunk) => chunk.split("\n```")[0]);
	const summaryCard = blocks.find((block) => block.startsWith("type: summary-card\n"));
	assert.ok(summaryCard, "summary-card example missing");
	assert.match(summaryCard, /^type: summary-card\nmetric: heart-rate\n/);
	assert.match(summaryCard, /\nlast: \d+$/);
	const rollupExplorer = blocks.find((block) => block.startsWith("type: rollup-explorer\n"));
	assert.ok(rollupExplorer, "rollup-explorer example missing");
	assert.doesNotMatch(markdown, /: undefined|: null/);
});
