/**
 * Generates the Health.md dashboard note: a living, in-vault reference that
 * documents every visualization with its use case, options, defaults, data
 * requirements, and a working `health-viz` example block.
 *
 * Kept free of Obsidian imports so node tests can build and assert on it.
 */
import {
	EXPORT_SOURCE_DESCRIPTORS,
	ParamDefinition,
	VisualizationCategory,
	VisualizationOption,
	VISUALIZATION_CATALOG,
	VISUALIZATION_CATEGORIES,
} from "./visualization-catalog";

export const DASHBOARD_NOTE_PATH = "Health Dashboard.md";

const CODE_FENCE = "```";

function escapeTableCell(text: string): string {
	return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function paramDefaultLabel(param: ParamDefinition): string {
	if (param.kind === "toggle") return `\`${param.defaultValue ? "true" : "false"}\``;
	if (param.defaultValue != null && String(param.defaultValue).length > 0) {
		return `\`${param.defaultValue}\``;
	}
	return "*(optional)*";
}

function paramDescriptionCell(param: ParamDefinition): string {
	let text = param.desc;
	if (param.kind === "select" && param.options.length > 0) {
		const values = param.options.map((option) => `\`${option.value}\``).join(", ");
		text += ` One of: ${values}.`;
	}
	if (param.optional && !/\boptional\b/i.test(text)) text += " Optional.";
	return escapeTableCell(text);
}

function buildExampleBlock(option: VisualizationOption): string {
	const lines: string[] = [`type: ${option.type}`];

	for (const param of option.params) {
		if (param.kind === "toggle") {
			lines.push(`${param.key}: ${param.defaultValue ? "true" : "false"}`);
			continue;
		}
		const value = param.defaultValue != null ? String(param.defaultValue).trim() : "";
		if (value) lines.push(`${param.key}: ${value}`);
	}

	lines.push(`last: ${option.defaultLast}`);
	if (option.defaultHeight != null) lines.push(`height: ${option.defaultHeight}`);

	return `${CODE_FENCE}health-viz\n${lines.join("\n")}\n${CODE_FENCE}`;
}

function exportSourcesLabel(option: VisualizationOption): string {
	const labels = (option.exportSources ?? [])
		.map((id) => EXPORT_SOURCE_DESCRIPTORS.find((descriptor) => descriptor.id === id)?.label ?? id);
	return labels.length > 0 ? labels.join(", ") : "Daily JSON";
}

function buildVisualizationSection(option: VisualizationOption): string {
	const parts: string[] = [];

	parts.push(`### ${option.label}`);
	parts.push(option.description);
	parts.push(`\`${option.type}\` · Works with: ${exportSourcesLabel(option)}`);

	if (option.exportNote) {
		parts.push(`> Note: ${option.exportNote}`);
	}

	if (option.params.length > 0) {
		const rows = [
			"| Option | Description | Default |",
			"| --- | --- | --- |",
			...option.params.map((param) =>
				`| \`${param.key}\` | ${paramDescriptionCell(param)} | ${paramDefaultLabel(param)} |`
			),
		];
		parts.push(rows.join("\n"));
	}

	parts.push(buildExampleBlock(option));
	return parts.join("\n\n");
}

function buildCategorySection(category: VisualizationCategory, options: VisualizationOption[]): string {
	const parts: string[] = [];
	parts.push(`## ${category.label}`);
	parts.push(category.description);
	for (const option of options) {
		parts.push(buildVisualizationSection(option));
	}
	return parts.join("\n\n");
}

export function buildDashboardMarkdown(pluginVersion: string): string {
	const parts: string[] = [];

	parts.push(`<!-- Generated by Health.md Visualizations v${pluginVersion}. Regenerate via the "Regenerate health dashboard" command. -->`);

	parts.push("# Health.md visualizations");

	parts.push(
		"Welcome! This note is a live reference for every visualization the Health.md Visualizations plugin can render. " +
		"Each chart below has a short description, its options and defaults, and a working example."
	);

	parts.push(
		"> [!important] Charts need real data\n" +
		"> The examples below render whatever health exports exist in your configured data folder " +
		"(plugin settings → Data folder). The plugin ships with no sample data — with an empty data folder, " +
		"charts show a friendly \"no data\" message instead.\n" +
		"> Don't have exports yet? Grab the app, export your health data into this vault, and every example comes alive:  \n" +
		"> 🍎 [Health.md on the App Store](https://apps.apple.com/us/app/health-md/id6757763969) · " +
		"🤖 [Health.md on Google Play](https://play.google.com/store/apps/details?id=com.healthmd.android)"
	);

	parts.push(
		"- **Edit any example freely** — change `last: 30` to another day count, tweak options, and the chart re-renders.\n" +
		"- Every chart also accepts `width` (pixels) and date ranges via `from` / `to` in place of `last`.\n" +
		"- To add a single chart anywhere in your notes, run the **Insert health visualization** command from the command palette.\n" +
		"- Reopen this note anytime from the heartbeat ribbon icon or the **Open health dashboard** command.\n" +
		"- This note is yours — the plugin never overwrites it unless you run **Regenerate health dashboard**, which rebuilds it with the latest charts and documentation."
	);

	const categorized = VISUALIZATION_CATEGORIES
		.filter((category) => category.id !== "all")
		.map((category) => ({
			category,
			options: VISUALIZATION_CATALOG.filter((option) => option.category === category.id),
		}))
		.filter((entry) => entry.options.length > 0);

	parts.push(
		`**Contents:** ${categorized
			.map((entry) => `[[#${entry.category.label}]]`)
			.join(" · ")}`
	);

	parts.push(`${VISUALIZATION_CATALOG.length} visualizations across ${categorized.length} categories.`);

	for (const entry of categorized) {
		parts.push(buildCategorySection(entry.category, entry.options));
	}

	return parts.join("\n\n") + "\n";
}
